Edetect_wav('paramFile','/Users/kait/Code/Grateful-DetEdit/Edetect_param_default.xlsx',...
        'tfFile','/Users/kait/Google Drive/TF_files/601_100416_invSensit_GC.tf',...
        'wavDir',{'/Users/kait/Google Drive/DCLDE_gray_set/DCL_HF_Data_gray/WAT_NC_01'},...
        'channel',1);