function ID_legend

global dPARAMS p dHANDLES
dHANDLES.hID = figure(10);
clf
% set up column sizes
rowCount = size(p.colorTab,1);
if isempty(p.mySpID)
    colCount = 2;
    w = [.75,.25];
else
    colCount = 3;
    w = [.3,.2,.5];
end
allRows = rowCount+4;
h = 1/allRows;% +1 to save room for title

% Set up window placement & size on screen
defaultPos=[0,0.2,0.03*colCount,.02*allRows];
% open and setup figure window
set(dHANDLES.hID, ...
    'NumberTitle','off', ...
    'Name','ID Legend',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos);

% Write heading
labelStr = 'ID Color Legend';
txtPos = [0 1-h 1 h];
dHANDLES.h10handles.headTxt = uicontrol(dHANDLES.hID, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',txtPos, ...
    'String',labelStr, ...
    'FontUnits','normalized',...
    'FontSize',.75,...
    'FontWeight','bold');

dPARAMS.ID_Toggle = ones(allRows,1);

% Put each color on a row
for iColor = 1:rowCount
    
    patchPos=[0, 1-((iColor+1)*h), w(1), h];
    dHANDLES.h10handles.colorbox{iColor} = uicontrol(dHANDLES.hID,...
        'Style','togglebutton',...
        'Units','normalized',...
        'Position',patchPos,...
        'BackgroundColor',p.colorTab(iColor,:),...
        'String','',...
        'Value',dPARAMS.ID_Toggle(rowCount),...
        'FontUnits','normalized',...
        'Callback', {@ID_toggle,iColor});
    
    labelPos=[w(1), 1-((iColor+1)*h), w(2), h];
    dHANDLES.h10handles.colorLabel{iColor} = uicontrol(dHANDLES.hID,...
        'Style','text',...
        'Units','normalized',...
        'Position',labelPos,...
        'String',num2str(iColor),...
        'FontUnits','normalized',...
        'FontSize',.5,...
        'FontWeight','bold');
    
    if ~isempty(p.mySpID)
        % if species labels are provided, add them as 3rd column
        if iColor<= length(p.mySpID)
            spPos=[sum(w(1:2)), 1-((iColor+1)*h), w(3), h];
            dHANDLES.h10handles.spLabel{iColor} = uicontrol(dHANDLES.hID,...
                'Style','text',...
                'Units','normalized',...
                'Position',spPos,...
                'String',p.mySpID{iColor},...
                'FontUnits','normalized',...
                'FontSize',.5,...
                'FontWeight','bold',...
                'HorizontalAlignment','left');
            
        end
    end
end

% add unlabeled:

% get default color
defaultColor = get(dHANDLES.LTSAsubs(1),'ColorOrder');  
iColor = iColor+3;
patchPos=[0, 1-((iColor)*h), w(1), h];
dHANDLES.h10handles.colorboxUnlabeled = uicontrol(dHANDLES.hID,...
    'Style','togglebutton',...
    'Units','normalized',...
    'Position',patchPos,...
    'BackgroundColor',defaultColor(1,:),...
    'String','',...
    'Value',dPARAMS.NoLabel_Toggle,...
    'FontUnits','normalized',...
    'Callback', {@ID_toggle,0});

labelPos=[w(1), 1-((iColor)*h), w(2), h];
dHANDLES.h10handles.colorLabelUnlabeled = uicontrol(dHANDLES.hID,...
    'Style','text',...
    'Units','normalized',...
    'Position',labelPos,...
    'String',0,...
    'FontUnits','normalized',...
    'FontSize',.5,...
    'FontWeight','bold');

spPos=[sum(w(1:2)), 1-((iColor)*h), w(3), h];
dHANDLES.h10handles.spLabelUnlabeled = uicontrol(dHANDLES.hID,...
    'Style','text',...
    'Units','normalized',...
    'Position',spPos,...
    'String','Unlabeled',...
    'FontUnits','normalized',...
    'FontSize',.5,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');

% Add false
iColor = iColor+1;
patchPos=[0, 1-((iColor)*h), w(1), h];
dHANDLES.h10handles.colorboxFD = uicontrol(dHANDLES.hID,...
    'Style','togglebutton',...
    'Units','normalized',...
    'Position',patchPos,...
    'BackgroundColor','red',...
    'String','',...
    'Value',dPARAMS.FD_Toggle,...
    'FontUnits','normalized',...
    'Callback', {@ID_toggle,99});

labelPos=[w(1), 1-((iColor)*h), w(2), h];
dHANDLES.h10handles.colorLabelFD = uicontrol(dHANDLES.hID,...
    'Style','text',...
    'Units','normalized',...
    'Position',labelPos,...
    'String',99,...
    'FontUnits','normalized',...
    'FontSize',.5,...
    'FontWeight','bold');

spPos=[sum(w(1:2)), 1-((iColor)*h), w(3), h];
dHANDLES.h10handles.spLabelFD = uicontrol(dHANDLES.hID,...
    'Style','text',...
    'Units','normalized',...
    'Position',spPos,...
    'String','False',...
    'FontUnits','normalized',...
    'FontSize',.5,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
