function ha = subplot_layout
ha(1) = axes('Units','normalized', ...
    'Position',[.08 .70 .9 .25], ...
    'XTickLabel','', ...
    'YTickLabel','');
ha(2) = axes('Units','normalized', ...
    'Position',[.08 .35 .9 .3], ...
    'XTickLabel','', ...
    'YTickLabel','');
ha(3) = axes('Units','normalized', ...
    'Position',[.08 .05 .9 .25], ...
    'XTickLabel','', ...
    'YTickLabel','');
